# Generated by Django 3.0.4 on 2020-03-08 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('articles', '0002_auto_20200308_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artilce_text',
            new_name='article_text',
        ),
    ]
